[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/laws"
  to = "/laws-regulations"
  status = 301

[[redirects]]
  from = "/tourism"
  to = "/tourism-culture"
  status = 301

[[redirects]]
  from = "/culture"
  to = "/tourism-culture"
  status = 301

# These pages now have real content - no redirects needed

# All major pages now have real content - no more coming soon redirects needed

[[redirects]]
  from = "/newsletter"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/consultations"
  to = "/consultation"
  status = 301

# Redirect to SPA for all pages
[[redirects]]
  from = "/*"
  to = "/index-spa.html"
  status = 200
  force = false