[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/laws"
  to = "/laws-regulations"
  status = 301

[[redirects]]
  from = "/tourism"
  to = "/tourism-culture"
  status = 301

[[redirects]]
  from = "/culture"
  to = "/tourism-culture"
  status = 301

# These pages now have real content - no redirects needed

[[redirects]]
  from = "/departments"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/policy"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/transparency"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/guidance"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/help"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/privacy"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/cookies"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/accessibility"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/terms"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/feedback"
  to = "/coming-soon"
  status = 302

[[redirects]]
  from = "/newsletter"
  to = "/coming-soon"
  status = 302

# Catch-all redirect for any other undefined pages
[[redirects]]
  from = "/*"
  to = "/coming-soon"
  status = 302
  force = false